In [12]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_recall_fscore_support

In [13]:
with open("../data/roberta/astro0.tsv") as f:
    dataset = pd.read_csv(f, delimiter='\t')
    
with open("../data/kg_inferences_on_astro0_1.csv") as f:
    inferences = pd.read_csv(f)
    
display(dataset.head(), inferences.head())

Unnamed: 0       judge                                              first  \
0           0  entailment  People with Virgo rising tend to be practical,...   
1           1  entailment  People with Virgo rising tend to be practical,...   
2           2  entailment  People with Virgo rising tend to be practical,...   
3           3  entailment  People with Virgo rising tend to be practical,...   
4           4  entailment  People with Virgo rising tend to be practical,...   

                                              second  
0      You have an ingenious, active and alert mind.  
1  Gaining knowledge and putting it to good use a...  
2  You strive for perfection and can be quite the...  
3  At times others can never be "good" enough to ...  
4  Finding fault with what's wrong with things is...

Unnamed: 0      inference
0           0     entailment
1           1     entailment
2           2     entailment
3           3        neutral
4           4  contradiction

In [14]:
C = confusion_matrix(dataset['judge'], inferences['inference'], labels=['contradiction', 'neutral', 'entailment'])

In [15]:
C

array([[  3,   5,   8],
       [270, 681, 537],
       [ 40, 126, 100]], dtype=int64)

In [16]:
results = precision_recall_fscore_support(dataset['judge'], inferences['inference'], labels=['contradiction', 'neutral', 'entailment'])

In [17]:
results  # columns is the labels. rows are precision, recall, fscore, support 

(array([0.00958466, 0.83866995, 0.15503876]),
 array([0.1875    , 0.45766129, 0.37593985]),
 array([0.01823708, 0.59217391, 0.21953897]),
 array([  16, 1488,  266], dtype=int64))