In [4]:
import csv

In [4]:
label_dict = {0:'contradiction', 1:'entailment', 2:'neutral'}  # ids used in the SNLI dataset.

In [13]:
# convert astrocorpus format to snli-sembert format for input into snli-sembert predictor.
with open('../data/example.csv', 'r') as csvfile:
    csvreader = csv.reader(csvfile)
    with open ('../data/example.tsv', 'w') as tsvfile:
        tsvwriter = csv.writer(tsvfile, delimiter='\t', lineterminator='\n')
        header = [0, 1, 2, 3, 4, 5, 6, 'sentence1', 'sentence2', 'label']
        tsvwriter.writerow(header)
        
        next(csvreader, None)  # skip the header.
        for row in csvreader:
            to_write = [0, 1, 2, 3, 4, 5, 6]
            if row[3] == 'na':
                continue
            elif int(row[3]) == 5:
                label = 'neutral'
            elif int(row[3]) > 5:
                label = 'contradiction'
            else:
                label = 'entailment'
            to_write.extend([row[1], row[2], label])
            tsvwriter.writerow(to_write)

In [13]:
# obtain ground truth labels and predicted labels from tsv files for evaluation.
true = []
with open('../data/example.tsv', 'r') as tsvfile:
    tsvreader = csv.reader(tsvfile, delimiter='\t')
    next(tsvreader, 1)  # skip header
    for row in tsvreader:
        true.append(row[-1])
pred = []
with open('../data/sembert_output/110320_astro_pred_results.tsv', 'r') as tsvfile:
    tsvreader = csv.reader(tsvfile, delimiter='\t')
    next(tsvreader, 1)  # skip header
    for row in tsvreader:
        pred.append(row[-1])

In [18]:
import numpy as np
from sklearn.metrics import precision_score
from sklearn.metrics import precision_recall_fscore_support

In [15]:
len(pred)

1770

In [16]:
scores = precision_score(true, pred, average=None)

In [19]:
scores = precision_recall_fscore_support(true, pred, average=None)

In [20]:
scores

(array([0.01036269, 0.17737003, 0.80555556]),
 array([0.375     , 0.21804511, 0.46774194]),
 array([0.02016807, 0.19561551, 0.59183673]),
 array([  16,  266, 1488], dtype=int64))

110320_astro_pred_results.tsv prediction results are bad. the prediction model was trained on snli training set but NOT fine-tuned on the 'astro' dataset.
some randomized fine-tuning training on 'astro' might be needed to predict better on the astro domain. (which means i will have to get the buggy training script to work...)